oc login -u=clustadm -p=qapw4all
  oc new-project nginxandmysql
  oc project nginxandmysql
  oc new-app nginx+mysql
  oc new-project myphpex
  oc project myphpex
  oc new-app php
  oc new-project glassfish
  oc project glassfish
  oc new-app glassfish
  oc new-project wildfly
  oc project wildfly
  oc new-app jboss/wildfly
  oc new-project liberty
  oc project liberty
  oc new-app websphere-liberty
  oc new-project orientdb
  oc project orientdb
  oc new-app orientdb
  oc new-project tomee
  oc project tomee
  oc new-app tomee
  oc new-project gcc
  oc project gcc
  oc new-app gcc
  oc new-project elixir
  oc project elixir
  oc new-app elixir
  oc new-project groovy
  oc project groovy
  oc new-app groovy
  oc new-project kapacitor
  oc project kapacitor
  oc new-app kapacitor
  oc new-project ros
  oc project ros
  oc new-app ros
  oc new-project tomcat
  oc project tomcat
  oc new-app tomcat
  oc new-project tomcat801
  oc project tomcat801
  oc new-app rossbachp/apache-tomcat8
  oc new-project openjdk1801
  oc project openjdk1801
  oc new-app openjdk
  oc new-project sso701
  oc project sso701
  oc new-app ukti/directory-sso
  oc new-project dotnet01
  oc project dotnet01
  oc new-app microsoft/dotnet 
  oc new-project jenkins01
  oc project jenkins01
  oc new-app jenkins
  oc new-project mariadb01
  oc project mariadb01
  oc new-app mariadb
  oc new-project mongo01
  oc project mongo01
  oc new-app mongo
  oc new-project mysql0101
  oc project mysql0101
  oc new-app mysql
  oc new-project node01
  oc project node01
  oc new-app node
