  oc login -u=clustadm -p=qapw4all
  oc delete project rubyex
  oc delete project ruby-hellowrld
  oc delete project puma-test-app
  oc delete project mysql1
  oc delete project helloworld-mysql
  oc delete project nginxandmysql
  oc delete project myphpex
  #oc delete project fluentd
  oc delete project fisjava01
  oc delete project fiskaraf01
  oc delete project jbossamq01
  oc delete project jbossdatagrid6501
  oc delete project jbossdatavirt6301
  oc delete project jbossdecision6201
  oc delete project jbossdecision6301
  oc delete project jbosseap6401
  oc delete project jbosseap7001
  oc delete project jbossproccess6301
  oc delete project jbosstomcat701
  oc delete project jbosstomcat801
  oc delete project openjdk1801
  oc delete project sso701
  oc delete project dotnet01
  oc delete project jenkins01
  oc delete project mariadb01
  oc delete project mongo01
  oc delete project mysql0101
  oc delete project node01
  oc delete project perl01
  oc delete project php01
  oc delete project postgresql01
  oc delete project python01
  oc delete project redis01
  oc delete project rubyruby
