#!/bin/bash

oc new-app alpine
oc new-appnginx
oc new-app httpd
oc new-app busybox
oc new-app redis
oc new-app ubuntu
oc new-app mongo
oc new-app memcached
oc new-app mysql
oc new-app node
oc new-app postgres
oc new-app registry
oc new-app golang
oc new-app hello-world
oc new-app centos
oc new-app consul
oc new-app php
oc new-app mariadb
oc new-app docker
oc new-app elasticsearch
oc new-app haproxy
oc new-app wordpress
oc new-app rabbitmq
oc new-app python
oc new-app ruby
oc new-app openjdk
oc new-app traefik
oc new-app logstash
oc new-app debian
oc new-app influxdb
oc new-app tomcat
oc new-app java
oc new-app swarm
oc new-app jenkins
oc new-app maven
oc new-app nextcloud
oc new-app kibana
oc new-app ghost
oc new-app telegraf
oc new-app cassandra
oc new-app kong
oc new-app drupal
oc new-app vault
oc new-app nats
oc new-app fedora
oc new-app jruby
oc new-app owncloud
oc new-app sonarqube
oc new-app gradle
oc new-app sentry
oc new-app solr
oc new-app perl
oc new-app neo4j
oc new-app rethinkdb
oc new-app amazonlinux
oc new-app groovy
oc new-app rocket.chat
oc new-app percona
oc new-app chronograf
oc new-app buildpack-deps
oc new-app erlang
oc new-app flink
oc new-app jetty
oc new-app redmine
oc new-app zookeeper
oc new-app pypy
oc new-app couchdb
oc new-app iojs
oc new-app joomla
oc new-app couchbase
oc new-app django
oc new-app mono
oc new-app eclipse-mosquitto
oc new-app nats-streaming
oc new-app piwik
oc new-app bash
oc new-app crate
oc new-app elixir
oc new-app ubuntu-debootstrap
oc new-app arangodb
oc new-app kapacitor
oc new-app adminer
oc new-app tomee
oc new-app haxe
oc new-app websphere-liberty
oc new-app opensuse
oc new-app oraclelinux
oc new-app orientdb
oc new-app gcc
oc new-app mongo-express
oc new-app rails
oc new-app ros
oc new-app neurodebian
oc new-app xwiki
oc new-app odoo
oc new-app clojure
oc new-app ibmjava
oc new-app rust
oc new-app aerospike
oc new-app irssi
