docker load -i hub-cfssl421.tar
docker load -i hub-documentation421.tar
docker load -i hub-jobrunner421.tar
docker load -i hub-logstash421.tar
docker load -i hub-nginx421.tar
docker load -i hub-postgres421.tar
docker load -i hub-registration421.tar
docker load -i hub-solr421.tar
docker load -i hub-webapp421.tar
docker load -i hub-zookeeper421.tar
