#!/bin/bash
#==============================================
# silly script to import 1000 docker images
# into OpenShift as image streams
# Author: Joel Sheppard
#==============================================

oc import-image 2717 --from gradle:latest --confirm
oc import-image 6567 --from mhart/alpine-node-auto:latest --confirm
oc import-image 2859 --from aptalca/home-automation-bridge:latest --confirm
oc import-image 9316 --from willfarrell/autoheal:latest --confirm
oc import-image 1040 --from azuresdk/autorest:latest --confirm
oc import-image 1431 --from xeroxmalf/rutorrent-autodl-irssi:latest --confirm
oc import-image 8465 --from gordonchan/auto-letsencrypt:latest --confirm
oc import-image 127 --from autopilotpattern/mysql:latest --confirm
oc import-image 9804 --from autopilotpattern/nginx:latest --confirm
oc import-image 2378 --from mesosphere/marathon-lb-autoscale:latest --confirm
oc import-image 9318 --from akshayubhat/dva-auto:latest --confirm
oc import-image 2900 --from autopilotpattern/consul:latest --confirm
oc import-image 1172 --from aweber/rabbitmq-autocluster:latest --confirm
oc import-image 2635 --from jsmitsnl/docker-email-autodiscover:latest --confirm
oc import-image 3621 --from automenta/javai:latest --confirm
oc import-image 7602 --from autocoin/cpuminer-multi:latest --confirm
oc import-image 8589 --from brndnmtthws/marathon-lb-autoscale:latest --confirm
oc import-image 2012 --from edgurgel/poxa-automated:latest --confirm
oc import-image 2934 --from vauxoo/odoo-80-image-shippable-auto:latest --confirm
oc import-image 1958 --from prologic/autodock:latest --confirm
oc import-image 1719 --from jrelva/nginx-autoindex:latest --confirm
oc import-image 8425 --from crossbario/autobahn-python:latest --confirm
oc import-image 4610 --from rehabstudio/autodns:latest --confirm
oc import-image 6647 --from pivotalrabbitmq/rabbitmq-autocluster:latest --confirm
oc import-image 8803 --from automatewebsite/jwebrobot-chrome:latest --confirm
oc import-image 4853 --from gavinmroy/alpine-rabbitmq-autocluster:latest --confirm
oc import-image 3135 --from bidibi/mongodb-automation:latest --confirm
oc import-image 1802 --from wilcoe/auto-sub:latest --confirm
oc import-image 4082 --from vidazoohub/kafka-lag-dcos-autoscaler:latest --confirm
oc import-image 1398 --from corfr/git-autoupdate:latest --confirm
oc import-image 3866 --from henrylv206/rabbitmq-autocluster:latest --confirm
oc import-image 3423 --from autocoin/autocoin:latest --confirm
oc import-image 9509 --from majamee/auto-dash-hls:latest --confirm
oc import-image 7938 --from sitespeedio/sitespeed.io-autobuild:latest --confirm
oc import-image 598 --from tedezed/slug-statefulset-autoscaler:latest --confirm
oc import-image 2968 --from autowp/autowp:latest --confirm
oc import-image 8946 --from vidazoohub/marathon-redis-autoscale:latest --confirm
oc import-image 6342 --from vidazoohub/mesos-cloudwatch-autoscale:latest --confirm
oc import-image 5377 --from cusspvz/autotune:latest --confirm
oc import-image 1711 --from snorremd/docker-slack-invite-automation:latest --confirm
oc import-image 2472 --from vidazoohub/marathon-lb-autoscaler:latest --confirm
oc import-image 7776 --from vidazoohub/kafka-lag-heroku-autoscaler:latest --confirm
oc import-image 8774 --from dketley/rabbitmq-autocluster:latest --confirm
oc import-image 307 --from kuberstack/kubernetes-rabbitmq-autocluster:latest --confirm
oc import-image 4377 --from vidazoohub/dcos-connections-autoscale:latest --confirm
oc import-image 8245 --from koding/koding-auto:latest --confirm
oc import-image 795 --from madflojo/automatron:latest --confirm
oc import-image 5093 --from vidazoohub/marathon-rabbit-autoscale:latest --confirm
oc import-image 3634 --from hortonworks/cloudbreak-autoscale:latest --confirm
oc import-image 7655 --from inquicker/vault-auto-unsealer:latest --confirm
oc import-image 3536 --from trinitymirror/aws-ecs-alb-service-autoscaler:latest --confirm
oc import-image 8634 --from bringg/rabbitmq-autocluster:latest --confirm
oc import-image 402 --from autodeskcloud/adp-spark:latest --confirm
oc import-image 2334 --from ijoijo/nginx-auto:latest --confirm
oc import-image 3645 --from wbuchwalter/autoscaler:latest --confirm
oc import-image 2201 --from funkygibbon/automysqlbackup:latest --confirm
oc import-image 1557 --from alvistack/automysqlbackup:latest --confirm
oc import-image 6638 --from timfallmk/packer-auto:latest --confirm
oc import-image 416 --from autoscalerdocker/pcf-aion-bosh-2:latest --confirm
oc import-image 8583 --from beamonlabs/autocv:latest --confirm
oc import-image 5933 --from autodeskls/rtts-ochostats:latest --confirm
oc import-image 2621 --from thunderscore/dockerhook-auto:latest --confirm
oc import-image 7249 --from autodeskls/ochothon:latest --confirm
oc import-image 3198 --from wbuchwalter/kubernetes-acs-engine-autoscaler:latest --confirm
oc import-image 6309 --from autoloanportal/ws_loan_application:latest --confirm
oc import-image 7875 --from autoloanportal/ws_account_details:latest --confirm
oc import-image 6756 --from appbricks/automation-tools-alpine:latest --confirm
oc import-image 7734 --from jeggers/jenkins-push-automatization:latest --confirm
oc import-image 1029 --from autoloanportal/app_auto_loan_processing:latest --confirm
oc import-image 1928 --from ilsuhov/automation_bot:latest --confirm
oc import-image 8053 --from guggero/autoplc:latest --confirm
oc import-image 7553 --from autoloanportal/ws_customer:latest --confirm
oc import-image 9640 --from onedayrex/autodockfile:latest --confirm
oc import-image 6896 --from alenkacz/marathon-rabbitmq-autoscale:latest --confirm
oc import-image 7525 --from hjacobs/kube-aws-autoscaler:latest --confirm
oc import-image 7775 --from chefdemo/automate-nginx:latest --confirm
oc import-image 6277 --from zacftw/cluster-autoscaler:latest --confirm
oc import-image 2876 --from wattpad/cluster-autoscaler:latest --confirm
oc import-image 268 --from appbricks/automation-tools:latest --confirm
oc import-image 5801 --from amouat/create-certs-auto:latest --confirm
oc import-image 3279 --from amouat/copy-certs-auto:latest --confirm
oc import-image 4758 --from unibeautify/autopep8:latest --confirm
oc import-image 5 --from mozilla/autograph:latest --confirm
oc import-image 8119 --from movingimage/acs-engine-autoscaler:latest --confirm
oc import-image 5646 --from hachque/nginx-autoproxy:latest --confirm
oc import-image 3936 --from trinitymirror/aws-ecs-autoscaler:latest --confirm
oc import-image 3545 --from autoloanprocessing/ws_customer:latest --confirm
oc import-image 3839 --from nakebod/autosubje:latest --confirm
oc import-image 8994 --from horjulf/rutorrent-autodl:latest --confirm
oc import-image 3145 --from orangecloudfoundry/cf-ops-automation:latest --confirm
oc import-image 4889 --from automationcalculator/automation-calculator-rails:latest --confirm
oc import-image 2726 --from autoscalerdocker/pcf-aion:latest --confirm
oc import-image 7989 --from carboncoop/autoinit:latest --confirm
oc import-image 7413 --from pgmahesh/autoscaler:latest --confirm
oc import-image 3933 --from onfido/k8s-rabbit-pod-autoscaler:latest --confirm
oc import-image 9733 --from aspettl/docker-email-autodiscover:latest --confirm
oc import-image 1760 --from dbonev/automate_quotes:latest --confirm
oc import-image 6118 --from dbonev/automate_policies:latest --confirm
oc import-image 3469 --from dbonev/automate_mongo:latest --confirm
oc import-image 2716 --from dbonev/automate_api_gateway:latest --confirm
oc import-image 7875 --from gradle:latest --confirm
oc import-image 3192 --from mhart/alpine-node-auto:latest --confirm
oc import-image 2135 --from aptalca/home-automation-bridge:latest --confirm
oc import-image 1652 --from willfarrell/autoheal:latest --confirm
oc import-image 3340 --from azuresdk/autorest:latest --confirm
oc import-image 3574 --from xeroxmalf/rutorrent-autodl-irssi:latest --confirm
oc import-image 4811 --from gordonchan/auto-letsencrypt:latest --confirm
oc import-image 5054 --from autopilotpattern/mysql:latest --confirm
oc import-image 9642 --from autopilotpattern/nginx:latest --confirm
oc import-image 593 --from mesosphere/marathon-lb-autoscale:latest --confirm
oc import-image 6089 --from akshayubhat/dva-auto:latest --confirm
oc import-image 6374 --from autopilotpattern/consul:latest --confirm
oc import-image 230 --from aweber/rabbitmq-autocluster:latest --confirm
oc import-image 2603 --from jsmitsnl/docker-email-autodiscover:latest --confirm
oc import-image 4968 --from automenta/javai:latest --confirm
oc import-image 7056 --from autocoin/cpuminer-multi:latest --confirm
oc import-image 4849 --from brndnmtthws/marathon-lb-autoscale:latest --confirm
oc import-image 5952 --from edgurgel/poxa-automated:latest --confirm
oc import-image 3352 --from vauxoo/odoo-80-image-shippable-auto:latest --confirm
oc import-image 4155 --from prologic/autodock:latest --confirm
oc import-image 8373 --from jrelva/nginx-autoindex:latest --confirm
oc import-image 1958 --from crossbario/autobahn-python:latest --confirm
oc import-image 2709 --from rehabstudio/autodns:latest --confirm
oc import-image 8955 --from pivotalrabbitmq/rabbitmq-autocluster:latest --confirm
oc import-image 2447 --from automatewebsite/jwebrobot-chrome:latest --confirm
oc import-image 7870 --from gavinmroy/alpine-rabbitmq-autocluster:latest --confirm
oc import-image 5592 --from bidibi/mongodb-automation:latest --confirm
oc import-image 7592 --from wilcoe/auto-sub:latest --confirm
oc import-image 8219 --from vidazoohub/kafka-lag-dcos-autoscaler:latest --confirm
oc import-image 5619 --from corfr/git-autoupdate:latest --confirm
oc import-image 4110 --from henrylv206/rabbitmq-autocluster:latest --confirm
oc import-image 3240 --from autocoin/autocoin:latest --confirm
oc import-image 3596 --from majamee/auto-dash-hls:latest --confirm
oc import-image 3389 --from sitespeedio/sitespeed.io-autobuild:latest --confirm
oc import-image 1898 --from tedezed/slug-statefulset-autoscaler:latest --confirm
oc import-image 4568 --from autowp/autowp:latest --confirm
oc import-image 9366 --from vidazoohub/marathon-redis-autoscale:latest --confirm
oc import-image 8082 --from vidazoohub/mesos-cloudwatch-autoscale:latest --confirm
oc import-image 7954 --from cusspvz/autotune:latest --confirm
oc import-image 4298 --from snorremd/docker-slack-invite-automation:latest --confirm
oc import-image 2754 --from vidazoohub/marathon-lb-autoscaler:latest --confirm
oc import-image 7893 --from vidazoohub/kafka-lag-heroku-autoscaler:latest --confirm
oc import-image 4674 --from dketley/rabbitmq-autocluster:latest --confirm
oc import-image 8919 --from kuberstack/kubernetes-rabbitmq-autocluster:latest --confirm
oc import-image 982 --from vidazoohub/dcos-connections-autoscale:latest --confirm
oc import-image 9463 --from koding/koding-auto:latest --confirm
oc import-image 5535 --from madflojo/automatron:latest --confirm
oc import-image 8230 --from vidazoohub/marathon-rabbit-autoscale:latest --confirm
oc import-image 6155 --from hortonworks/cloudbreak-autoscale:latest --confirm
oc import-image 1764 --from inquicker/vault-auto-unsealer:latest --confirm
oc import-image 1993 --from trinitymirror/aws-ecs-alb-service-autoscaler:latest --confirm
oc import-image 8584 --from bringg/rabbitmq-autocluster:latest --confirm
oc import-image 387 --from autodeskcloud/adp-spark:latest --confirm
oc import-image 4410 --from ijoijo/nginx-auto:latest --confirm
oc import-image 6405 --from wbuchwalter/autoscaler:latest --confirm
oc import-image 3659 --from funkygibbon/automysqlbackup:latest --confirm
oc import-image 1923 --from alvistack/automysqlbackup:latest --confirm
oc import-image 6033 --from timfallmk/packer-auto:latest --confirm
oc import-image 7670 --from autoscalerdocker/pcf-aion-bosh-2:latest --confirm
oc import-image 2942 --from beamonlabs/autocv:latest --confirm
oc import-image 7859 --from autodeskls/rtts-ochostats:latest --confirm
oc import-image 7555 --from thunderscore/dockerhook-auto:latest --confirm
oc import-image 1735 --from autodeskls/ochothon:latest --confirm
oc import-image 7343 --from wbuchwalter/kubernetes-acs-engine-autoscaler:latest --confirm
oc import-image 6096 --from autoloanportal/ws_loan_application:latest --confirm
oc import-image 4319 --from autoloanportal/ws_account_details:latest --confirm
oc import-image 2318 --from appbricks/automation-tools-alpine:latest --confirm
oc import-image 1624 --from jeggers/jenkins-push-automatization:latest --confirm
oc import-image 3199 --from autoloanportal/app_auto_loan_processing:latest --confirm
oc import-image 9781 --from ilsuhov/automation_bot:latest --confirm
oc import-image 8963 --from guggero/autoplc:latest --confirm
oc import-image 1815 --from autoloanportal/ws_customer:latest --confirm
oc import-image 8545 --from onedayrex/autodockfile:latest --confirm
oc import-image 3760 --from alenkacz/marathon-rabbitmq-autoscale:latest --confirm
oc import-image 846 --from hjacobs/kube-aws-autoscaler:latest --confirm
oc import-image 3731 --from chefdemo/automate-nginx:latest --confirm
oc import-image 8227 --from zacftw/cluster-autoscaler:latest --confirm
oc import-image 9583 --from wattpad/cluster-autoscaler:latest --confirm
oc import-image 2130 --from appbricks/automation-tools:latest --confirm
oc import-image 8792 --from amouat/create-certs-auto:latest --confirm
oc import-image 5298 --from amouat/copy-certs-auto:latest --confirm
oc import-image 8181 --from unibeautify/autopep8:latest --confirm
oc import-image 4515 --from mozilla/autograph:latest --confirm
oc import-image 8477 --from movingimage/acs-engine-autoscaler:latest --confirm
oc import-image 851 --from hachque/nginx-autoproxy:latest --confirm
oc import-image 7784 --from trinitymirror/aws-ecs-autoscaler:latest --confirm
oc import-image 4679 --from autoloanprocessing/ws_customer:latest --confirm
oc import-image 6778 --from nakebod/autosubje:latest --confirm
oc import-image 6605 --from horjulf/rutorrent-autodl:latest --confirm
oc import-image 7256 --from orangecloudfoundry/cf-ops-automation:latest --confirm
oc import-image 988 --from automationcalculator/automation-calculator-rails:latest --confirm
oc import-image 915 --from autoscalerdocker/pcf-aion:latest --confirm
oc import-image 8944 --from carboncoop/autoinit:latest --confirm
oc import-image 8257 --from pgmahesh/autoscaler:latest --confirm
oc import-image 4119 --from onfido/k8s-rabbit-pod-autoscaler:latest --confirm
oc import-image 9651 --from aspettl/docker-email-autodiscover:latest --confirm
oc import-image 1728 --from dbonev/automate_quotes:latest --confirm
oc import-image 8207 --from dbonev/automate_policies:latest --confirm
oc import-image 9121 --from dbonev/automate_mongo:latest --confirm
oc import-image 824 --from dbonev/automate_api_gateway:latest --confirm
oc import-image 1887 --from atlassian/bitbucket-server:latest --confirm
oc import-image 1477 --from bittorrent/sync:latest --confirm
oc import-image 4207 --from bitnami/redis:latest --confirm
oc import-image 8903 --from bitnami/wordpress:latest --confirm
oc import-image 5503 --from kylemanna/bitcoind:latest --confirm
oc import-image 8805 --from bitnami/mariadb:latest --confirm
oc import-image 4876 --from bitnami/nginx:latest --confirm
oc import-image 107 --from bitnami/php-fpm:latest --confirm
oc import-image 5347 --from bitnami/minideb:latest --confirm
oc import-image 6489 --from bitnami/apache:latest --confirm
oc import-image 3602 --from bitnami/mongodb:latest --confirm
oc import-image 276 --from cptactionhank/atlassian-bitbucket:latest --confirm
oc import-image 3796 --from bitnami/redmine:latest --confirm
oc import-image 6203 --from bitnami/node:latest --confirm
oc import-image 8767 --from bitnami/magento:latest --confirm
oc import-image 2704 --from bitnami/laravel:latest --confirm
oc import-image 1046 --from bitnami/dokuwiki:latest --confirm
oc import-image 6656 --from bitnami/postgresql:latest --confirm
oc import-image 8896 --from amacneil/bitcoin:latest --confirm
oc import-image 4463 --from blacklabelops/bitbucket:latest --confirm
oc import-image 985 --from bitnami/testlink:latest --confirm
oc import-image 2960 --from bitnami/tomcat:latest --confirm
oc import-image 2439 --from bitnami/phabricator:latest --confirm
oc import-image 5790 --from fluent/fluent-bit:latest --confirm
oc import-image 309 --from bitnami/mysql:latest --confirm
oc import-image 3545 --from bitnami/cassandra:latest --confirm
oc import-image 6451 --from bitnami/moodle:latest --confirm
oc import-image 5722 --from bitnami/suitecrm:latest --confirm
oc import-image 7021 --from smartapps/bitbucket-pipelines-php-mysql:latest --confirm
oc import-image 7859 --from felixweis/bitcoind:latest --confirm
oc import-image 4180 --from bitnami/ruby:latest --confirm
oc import-image 6817 --from bitnami/tensorflow-serving:latest --confirm
oc import-image 405 --from bitnami/jenkins:latest --confirm
oc import-image 5314 --from bitnami/ghost:latest --confirm
oc import-image 4614 --from bitnami/opencart:latest --confirm
oc import-image 7349 --from bitnami/jasperreports:latest --confirm
oc import-image 7879 --from bitnami/joomla:latest --confirm
oc import-image 1542 --from bitnami/kafka:latest --confirm
oc import-image 1903 --from bitnami/rabbitmq:latest --confirm
oc import-image 5770 --from bitnami/discourse:latest --confirm
oc import-image 4705 --from seegno/bitcoind:latest --confirm
oc import-image 9002 --from ruimarinho/bitcoin-core:latest --confirm
oc import-image 9221 --from bitnami/rails:latest --confirm
oc import-image 3157 --from bitnami/elasticsearch:latest --confirm
oc import-image 9500 --from bitnami/odoo:latest --confirm
oc import-image 8267 --from bitnami/memcached:latest --confirm
oc import-image 4164 --from bitnami/kibana:latest --confirm
oc import-image 8087 --from bitriseio/docker-bitrise-base:latest --confirm
oc import-image 2784 --from bitnami/owncloud:latest --confirm
oc import-image 122 --from bitnami/drupal:latest --confirm
oc import-image 647 --from bitnami/minideb-extras:latest --confirm
oc import-image 7319 --from bitshares/bitshares-core:latest --confirm
oc import-image 2621 --from bitnami/mediawiki:latest --confirm
oc import-image 4829 --from bitnami/parse:latest --confirm
oc import-image 2398 --from bitnami/prestashop:latest --confirm
oc import-image 4632 --from bitnami/phpbb:latest --confirm
oc import-image 1557 --from bitnami/wildfly:latest --confirm
oc import-image 7977 --from bitnami/zookeeper:latest --confirm
oc import-image 4260 --from h0tbird/bitbucket:latest --confirm
oc import-image 6666 --from bitwarden/api:latest --confirm
oc import-image 8384 --from bitnami/kubeless-ui:latest --confirm
oc import-image 2398 --from bitbuyio/minergate-cli:latest --confirm
oc import-image 6202 --from bitnami/kubeless-controller:latest --confirm
oc import-image 1199 --from steigr/atlassian-bitbucket:latest --confirm
oc import-image 9637 --from bitergia/elasticsearch:latest --confirm
oc import-image 1061 --from fluent/fluent-bit-kubernetes-daemonset:latest --confirm
oc import-image 5242 --from laurentverbruggen/concourse-bitbucket-pullrequest-resource:latest --confirm
oc import-image 7767 --from bitnami/phpmyadmin:latest --confirm
oc import-image 9798 --from ecometrica/concourse-resource-bitbucket:latest --confirm
oc import-image 5272 --from bitnami/osclass:latest --confirm
oc import-image 8899 --from bitnami/matomo:latest --confirm
oc import-image 1328 --from chrisprice/monzo-bitcoin-webhook:latest --confirm
oc import-image 3224 --from bitwarden/web:latest --confirm
oc import-image 1024 --from bitnami/piwik:latest --confirm
oc import-image 9743 --from edbizarro/bitbucket-pipelines-php7:latest --confirm
oc import-image 9913 --from bitergia/kibiter:latest --confirm
oc import-image 3200 --from bitriseio/website-docker-base-env:latest --confirm
oc import-image 4782 --from bitnami/monocular-api:latest --confirm
oc import-image 626 --from shyxormz/bitbucket-build-status-resource:latest --confirm
oc import-image 5186 --from bitwarden/setup:latest --confirm
oc import-image 2680 --from bitriseio/docker-bitrise-base-alpha:latest --confirm
oc import-image 6788 --from mm62/concourse-bitbucket-pullrequest-resource:latest --confirm
oc import-image 8233 --from chrisprice/stripe-bitcoin:latest --confirm
oc import-image 2060 --from ruken/concourse-bitbucket-buildstatus:latest --confirm
oc import-image 499 --from bitwarden/admin:latest --confirm
oc import-image 5936 --from mperrotte/bitbucket-build-notification-resource:latest --confirm
oc import-image 7946 --from thebeefcake/concourse-bitbucket-resource:latest --confirm
oc import-image 9919 --from bitwarden/nginx:latest --confirm
oc import-image 7535 --from cathive/concourse-bitbucket-pullrequest-resource:latest --confirm
oc import-image 4044 --from amerine/fluent-bit:latest --confirm
oc import-image 865 --from zarplata/concourse-git-bitbucket-pr-resource:latest --confirm
oc import-image 6501 --from johannesrudolph/concourse-resource-bitbucket:latest --confirm
oc import-image 4013 --from alvarezcl/concourse-bitbucket-resource:latest --confirm
oc import-image 5394 --from bitwarden/attachments:latest --confirm
oc import-image 2951 --from alvarezcl/concourse-build-resource-bitbucket:latest --confirm
oc import-image 403 --from bitwarden/icons:latest --confirm
oc import-image 9849 --from bitnami/python:latest --confirm
oc import-image 9364 --from bitwarden/identity:latest --confirm
oc import-image 5276 --from bitwarden/mssql:latest --confirm
oc import-image 7392 --from mperrotte/bitbucket-pullrequest-resource:latest --confirm
oc import-image 1787 --from tianon/true:latest --confirm
oc import-image 6046 --from bytekast/docker-pentaho-ce-6.0:latest --confirm
oc import-image 7067 --from byteflair/swagger-editor:latest --confirm
oc import-image 8072 --from byteflair/raml-editor:latest --confirm
oc import-image 9958 --from bytepixie/actordb-rancher:latest --confirm
oc import-image 6058 --from ozhiganov/bytecoin-miner:latest --confirm
oc import-image 1971 --from rootlogin/byteball-hub:latest --confirm
oc import-image 1756 --from stilliard/bytemark-symbiosis:latest --confirm
oc import-image 1649 --from creepycat/byte-wallet:latest --confirm
oc import-image 7216 --from bytepixie/cockroachdb-rancher:latest --confirm
oc import-image 2994 --from bytekast/docker-pentaho-ce-5.4:latest --confirm
oc import-image 7516 --from byteflair/docker-maven-private:latest --confirm
oc import-image 1271 --from bytepixie/actordb:latest --confirm
oc import-image 623 --from byteflair/rabbitmq-stomp:latest --confirm
oc import-image 7308 --from bytesized/filebot:latest --confirm
oc import-image 5788 --from rafalsladek/bytecoin-docker:latest --confirm
oc import-image 7841 --from bytesized/appbox-plex:latest --confirm
oc import-image 1977 --from bytepark/bytefile:latest --confirm
oc import-image 6523 --from snipa/bytecoin-miner:latest --confirm
oc import-image 7123 --from geoint/read-bytes:latest --confirm
oc import-image 651 --from bytecodetech/maven-npm:latest --confirm
oc import-image 8848 --from bytecubed/bytecubed-terraform:latest --confirm
oc import-image 6284 --from bytesized/sickrage:latest --confirm
oc import-image 112 --from bytesized/nzbget:latest --confirm
oc import-image 8708 --from bytesized/couchpotato:latest --confirm
oc import-image 7021 --from bytesized/vnc:latest --confirm
oc import-image 6133 --from carlyledavis/bytecubed-java-ci:latest --confirm
oc import-image 7386 --from bytesized/radarr:latest --confirm
oc import-image 4552 --from bytesized/plex-requests:latest --confirm
oc import-image 2628 --from bytefader/docker-maven3-jdk8-alpine:latest --confirm
oc import-image 1074 --from bytesized/cardigann:latest --confirm
oc import-image 9377 --from bytekode/alpine-toolchain:latest --confirm
oc import-image 2156 --from bytecubed/sbir-one:latest --confirm
oc import-image 4396 --from bytesized/znc:latest --confirm
oc import-image 9878 --from bytekode/maven-jdk7:latest --confirm
oc import-image 6212 --from bytesized/base:latest --confirm
oc import-image 6722 --from bytesized/subsonic:latest --confirm
oc import-image 5288 --from carlyledavis/bytecubed-sonar:latest --confirm
oc import-image 1384 --from bytecubed/datascience-dataio-mysql-test:latest --confirm
oc import-image 1074 --from bytesized/resilio-sync:latest --confirm
oc import-image 4074 --from bytekode/node:latest --confirm
oc import-image 5840 --from bytepark/alpine-drupal8:latest --confirm
oc import-image 4534 --from bytepark/alpine-php7.1-fpm:latest --confirm
oc import-image 6702 --from creepycat/byte-miner:latest --confirm
oc import-image 9774 --from bytefader/docker-nodejs6-maven3-jdk8-alpine:latest --confirm
oc import-image 8653 --from bytesized/rocketchat:latest --confirm
oc import-image 809 --from pmiklos/byteball-testnet:latest --confirm
oc import-image 1843 --from carlyledavis/bytecubed-chrome-selenium:latest --confirm
oc import-image 7732 --from jschwerberg/bytecoin-miner:latest --confirm
oc import-image 5645 --from pmiklos/byteball-hub:latest --confirm
oc import-image 7350 --from byteflair/ssh-rsync:latest --confirm
oc import-image 7904 --from bytepark/alpine-nginx-php7:latest --confirm
oc import-image 7958 --from byteheroes/awscli:latest --confirm
oc import-image 2413 --from bytesized/murmur:latest --confirm
oc import-image 7672 --from bytesized/rutorrent:latest --confirm
oc import-image 928 --from gisjedi/scale-read-bytes:latest --confirm
oc import-image 9928 --from byteheroes/php-fpm-laravel:latest --confirm
oc import-image 395 --from carlyledavis/bytecubed-elasticsearch:latest --confirm
oc import-image 6364 --from bytesized/plex:latest --confirm
oc import-image 3073 --from pmiklos/byteball-devnet:latest --confirm
oc import-image 7577 --from bytesized/syncthing:latest --confirm
oc import-image 5987 --from bytepark/docker-php7-xdebug:latest --confirm
oc import-image 1525 --from bytesized/debian-base:latest --confirm
oc import-image 3561 --from bytepark/alpine-nginx:latest --confirm
oc import-image 2316 --from agodbehere/bytecubed-datascience-build:latest --confirm
oc import-image 8362 --from bytesized/plexpy:latest --confirm
oc import-image 7294 --from bytesized/sonarr:latest --confirm
oc import-image 2858 --from bytesmith/rclient:latest --confirm
oc import-image 6832 --from carlyledavis/bytecubed-terraform:latest --confirm
oc import-image 6107 --from bytekast/docker-pentaho-ce-5.3:latest --confirm
oc import-image 9674 --from secmap/bytes_1_gram:latest --confirm
oc import-image 2752 --from bytesized/deluge:latest --confirm
oc import-image 9903 --from bytesizedgames/backend_runner:latest --confirm
oc import-image 8209 --from byteflair/node:latest --confirm
oc import-image 757 --from secmap/bytes_2_gram:latest --confirm
oc import-image 7625 --from bytekast/docker-lamp-precise:latest --confirm
oc import-image 1363 --from bytekast/docker-pentaho-base:latest --confirm
oc import-image 1044 --from byteflair/php:latest --confirm
oc import-image 7369 --from bytefeld/build-container:latest --confirm
oc import-image 6534 --from byteco/nodejs:latest --confirm
oc import-image 628 --from byteflair/docker-sonar-check:latest --confirm
oc import-image 256 --from bytepoet/v1:latest --confirm
oc import-image 7493 --from byte13/dockerdokuwiki:latest --confirm
oc import-image 3815 --from bytesizedalex/nmap:latest --confirm
oc import-image 563 --from pmiklos/byteball-devnet-wallet:latest --confirm
oc import-image 32 --from byteflair/grails:latest --confirm
oc import-image 3728 --from byteflair/kibana-marvel:latest --confirm
oc import-image 3187 --from byteworld/first:latest --confirm
oc import-image 2460 --from bytequest/eclipse-gnuarm-embedded:latest --confirm
oc import-image 5847 --from bytepoet/v1helper:latest --confirm
oc import-image 8602 --from bytesized/jackett:latest --confirm
oc import-image 1569 --from bytekode/alpine:latest --confirm
oc import-image 7906 --from bytesized/headphones:latest --confirm
oc import-image 833 --from bytewaregmbh/elasticsearch:latest --confirm
oc import-image 5705 --from bytepoet/icanhaz:latest --confirm
oc import-image 6542 --from bytefoolish/bytefoolish.me:latest --confirm
oc import-image 8439 --from nodeschool/bytewiser:latest --confirm
oc import-image 1148 --from bytequest/android:latest --confirm
oc import-image 4842 --from thehajime/byte-unixbench:latest --confirm
oc import-image 3896 --from byteback/votingapp_voting-app:latest --confirm
oc import-image 5794 --from aroygreenfeld/centos7-django:latest --confirm
oc import-image 327 --from amaysim/cookiecutter:latest --confirm
oc import-image 7248 --from opensystemlab/cookiemonster:latest --confirm
oc import-image 7253 --from helder/cookiecutter:latest --confirm
oc import-image 9535 --from archomeda/cookie-omega-discord-bot:latest --confirm
oc import-image 2966 --from cookiecutterdjango/base:latest --confirm
oc import-image 1135 --from cookiegamermel/testsihm:latest --confirm
oc import-image 6548 --from dkeis/fortune-cookie:latest --confirm
oc import-image 3276 --from pypi/cookiecutter-django:latest --confirm
oc import-image 2455 --from mercury/cookie-monster:latest --confirm
oc import-image 2052 --from hexletboy/cookies_exercise:latest --confirm
oc import-image 9000 --from arogudl/nginx-cookie:latest --confirm
oc import-image 4911 --from cookiecutter/cookiecutter:latest --confirm
oc import-image 4127 --from pypi/emencia-cookie-law:latest --confirm
oc import-image 7164 --from zwervertje/cookiecutter:latest --confirm
oc import-image 8442 --from opensystemlab/cookiemonsterworker:latest --confirm
oc import-image 7075 --from jwisgerhof/docker-jwt-cookie-setter:latest --confirm
oc import-image 8333 --from flemay/cookiecutter:latest --confirm
oc import-image 7854 --from rubygem/cookie_extractor:latest --confirm
oc import-image 4517 --from kujyp/hackday-cookie-jar:latest --confirm
oc import-image 4931 --from rschloming/cookie:latest --confirm
oc import-image 8303 --from capitains/cookiecutter-guidelines:latest --confirm
oc import-image 433 --from mercury/hgi-cookie-monster:latest --confirm
oc import-image 3518 --from dpetzold/ubuntu-latest-pip3-uwsgi-django-cookiecutter:latest --confirm
oc import-image 9205 --from nevkontakte/hsts-cookie:latest --confirm
oc import-image 7123 --from jasonamyers/cookies:latest --confirm
oc import-image 8972 --from richarddli/cookie:latest --confirm
oc import-image 7881 --from cookieisaac/haproxy:latest --confirm
oc import-image 8289 --from zwervertje/django-cookiecutter-dev:latest --confirm
oc import-image 8922 --from cookie/hadoop-cookie:latest --confirm
oc import-image 1383 --from neverlanctf/cookie_monster:latest --confirm
oc import-image 1599 --from tbone255/cookie:latest --confirm
oc import-image 3086 --from cookieisaac/ascbase:latest --confirm
oc import-image 162 --from pierrickl/dataprivacytool-cookiemanager:latest --confirm
oc import-image 8621 --from pierrickl/gdprtool-cookiechecker:latest --confirm
oc import-image 9220 --from cookieisaac/sinatra:latest --confirm
oc import-image 416 --from cookielab/alpine:latest --confirm
oc import-image 3523 --from cookiemonstero/firefox-vnc:latest --confirm
oc import-image 2507 --from thuvh/sloria-cookiecutter-flask:latest --confirm
oc import-image 7911 --from cookieisaac/hello-world:latest --confirm
oc import-image 2608 --from cookieisaac/writing-docker-in-c:latest --confirm
oc import-image 3939 --from cookieisaac/hello-web:latest --confirm
oc import-image 4807 --from cookiengineer/lycheejs:latest --confirm
oc import-image 6425 --from cookiedom/node:latest --confirm
oc import-image 3536 --from cookierookie/helloworld:latest --confirm
oc import-image 7435 --from cookieisaac/docker-whale:latest --confirm
oc import-image 4719 --from cookie/mycookiedocker:latest --confirm
oc import-image 2512 --from cookieisaac/videoplayer:latest --confirm
oc import-image 1106 --from cookie/dkutil:latest --confirm
oc import-image 5598 --from cookiecavekeeper/demo-node:latest --confirm
oc import-image 8647 --from terragontech/cookie_sync_api:latest --confirm
oc import-image 1533 --from cookiecavekeeper/demo-php:latest --confirm
oc import-image 3962 --from cookieisaac/ubuntu-ike:latest --confirm
oc import-image 6678 --from cookiecavekeeper/demo-java:latest --confirm
oc import-image 848 --from cookiecavekeeper/demo-static:latest --confirm
oc import-image 3026 --from skasturi/cookie-test:latest --confirm
oc import-image 1081 --from mjhoffman65/down-with-the-cookie:latest --confirm
oc import-image 8797 --from dpetzold/ubuntu-pip3-uwsgi-django-cookiecutter:latest --confirm
oc import-image 3943 --from cookieisaac/data-volume-image:latest --confirm
oc import-image 8858 --from lecourtoisn/cookies:latest --confirm
oc import-image 4325 --from cookiegamermel/docker-whale:latest --confirm
oc import-image 9414 --from zhukovever/docker-cookie-app-api:latest --confirm
oc import-image 6821 --from cookiedom/directory:latest --confirm
oc import-image 4271 --from cescoferraro/cookiecutter:latest --confirm
oc import-image 5039 --from czeslavo/cookies-api:latest --confirm
oc import-image 6972 --from seungkyua/cookiemonster:latest --confirm
oc import-image 6739 --from yaronpr/cookies:latest --confirm
oc import-image 9723 --from fenwickelliott/fresh-cookie:latest --confirm
oc import-image 9414 --from cookiedocker/debian-fhem:latest --confirm
oc import-image 7936 --from cookiedom/originator:latest --confirm
oc import-image 4679 --from jamrizzi/cross-domain-cookies:latest --confirm
oc import-image 5461 --from akhan/cookie-app:latest --confirm
oc import-image 2172 --from parafernalia/cookiecutter-django:latest --confirm
oc import-image 486 --from moogar0880/cookiecutter:latest --confirm
oc import-image 230 --from cookiengineer/lycheejs-mini:latest --confirm
oc import-image 7694 --from cookiebandit/products-api:latest --confirm
oc import-image 5225 --from c3sr/js-cookie:latest --confirm
oc import-image 5808 --from pwillie/oidc-ingress:latest --confirm
oc import-image 247 --from c3sr/cookies:latest --confirm
oc import-image 4287 --from henrikbaerbak/cookie:latest --confirm
oc import-image 9148 --from simulalex/fortune-cookie-api:latest --confirm
oc import-image 1535 --from cookie2016/googlecontainer:latest --confirm
oc import-image 3885 --from fenwickelliott/cookie:latest --confirm
oc import-image 7523 --from tcohen/talcookie:latest --confirm
oc import-image 1284 --from cookie2016/elasticsearch:latest --confirm
oc import-image 5721 --from platypew/cookiemonster:latest --confirm
oc import-image 377 --from cookiedom/service:latest --confirm
oc import-image 7339 --from cookielab/aws-cli:latest --confirm
oc import-image 7484 --from cookie2016/kibana:latest --confirm
oc import-image 6685 --from cookielab/kubectl:latest --confirm
oc import-image 531 --from nerc/zeppelin-connect:latest --confirm
oc import-image 9725 --from cookie2016/fluentd-elasticsearch:latest --confirm
oc import-image 94 --from 17media/fortuned:latest --confirm
oc import-image 7088 --from mceloud/cookiecutter:latest --confirm
oc import-image 525 --from cookielab/nodejs:latest --confirm
oc import-image 736 --from anujkhanna/docker-cookiecutter-python:latest --confirm
oc import-image 5003 --from cookie83610/firstrepo:latest --confirm
oc import-image 9899 --from kenjones/cookiecutter:latest --confirm
oc import-image 8910 --from ethanjh3/cookie:latest --confirm
oc import-image 1850 --from abousselmi/docker-cookiecutter:latest --confirm
oc import-image 2684 --from ubuntu-upstart:latest --confirm
oc import-image 7120 --from ceph/daemon:latest --confirm
oc import-image 1741 --from fluent/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 5119 --from bankiru/git-daemon:latest --confirm
oc import-image 3576 --from deis/store-daemon:latest --confirm
oc import-image 109 --from mkodockx/docker-guacamole-daemon:latest --confirm
oc import-image 6751 --from cdxvirt/ceph-daemon:latest --confirm
oc import-image 4192 --from madcatsu/airvideohd-server-daemon:latest --confirm
oc import-image 6770 --from osminogin/electrum-daemon:latest --confirm
oc import-image 457 --from fluent/fluent-bit-kubernetes-daemonset:latest --confirm
oc import-image 1040 --from atlassian/pipelines-docker-daemon:latest --confirm
oc import-image 4945 --from computeronix/storjshare-daemon:latest --confirm
oc import-image 1700 --from seedbloom/storjshare-daemon:latest --confirm
oc import-image 6772 --from iqucom/php-daemon-container:latest --confirm
oc import-image 9334 --from iqrfsdk/iqrf-daemon-webapp:latest --confirm
oc import-image 9103 --from madcatsu/storjshare-multi-daemon:latest --confirm
oc import-image 4489 --from coding4m/dnswall-daemon:latest --confirm
oc import-image 3729 --from daemoninc/prometheusd:latest --confirm
oc import-image 4900 --from bestmike007/weave-daemon:latest --confirm
oc import-image 3042 --from wifiplug/xray-daemon-alpine:latest --confirm
oc import-image 6871 --from s1061123/cni-dhcp-daemon:latest --confirm
oc import-image 815 --from tutum/weave-daemon:latest --confirm
oc import-image 1559 --from deisci/store-daemon:latest --confirm
oc import-image 6542 --from adun153/fluentd-kubernetes-daemonset-logzio:latest --confirm
oc import-image 1100 --from livingobjects/longback-daemon:latest --confirm
oc import-image 9023 --from linuxkit/host-timesync-daemon:latest --confirm
oc import-image 8177 --from bloxoss/daemon-scheduler:latest --confirm
oc import-image 4021 --from ceph/daemon-base:latest --confirm
oc import-image 4567 --from tgogoi/infoblox-cni-daemon:latest --confirm
oc import-image 2464 --from daemoninc/etcdd:latest --confirm
oc import-image 8382 --from devliftmike/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 9995 --from cotoami/kubernetes-fluentd-daemonset:latest --confirm
oc import-image 9644 --from hokiegeek/donde-estas-daemon:latest --confirm
oc import-image 7940 --from victoru/fluent-bit-kubernetes-daemonset:latest --confirm
oc import-image 2124 --from stackato/loadbalancer-daemon:latest --confirm
oc import-image 5494 --from informaticslab/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 9090 --from cmsj/avahi-daemon:latest --confirm
oc import-image 7483 --from stackatodev/loadbalancer-daemon:latest --confirm
oc import-image 1713 --from daemoninc/guacamoled:latest --confirm
oc import-image 8578 --from ameir/ecs-daemonset:latest --confirm
oc import-image 1492 --from daemoninc/node_exporterd:latest --confirm
oc import-image 6459 --from starkandwayne/shield-daemon:latest --confirm
oc import-image 1547 --from dippynark/ceph-daemon:latest --confirm
oc import-image 9955 --from fr8r/daemontest:latest --confirm
oc import-image 5334 --from logzloggingk8s/daemonset-fluentd-logz:latest --confirm
oc import-image 5438 --from gforgegroup/gforge-next-daemon:latest --confirm
oc import-image 9778 --from daemonza/testapi:latest --confirm
oc import-image 8224 --from coding4m/proxywall-daemon:latest --confirm
oc import-image 7337 --from yieldr/aws-cloudwatch-daemon:latest --confirm
oc import-image 9353 --from rohitshekhar/daemon:latest --confirm
oc import-image 2130 --from daemonza/helmet:latest --confirm
oc import-image 6125 --from csainty/ceph-daemon:latest --confirm
oc import-image 8686 --from fcoelho/phabricator-daemons:latest --confirm
oc import-image 2731 --from elsdoerfer/acme-daemon:latest --confirm
oc import-image 1490 --from infoblox/cni-infoblox-daemon:latest --confirm
oc import-image 409 --from mirantis/k8s-daemonupgradecontroller:latest --confirm
oc import-image 1516 --from iwaydev/backend-driver2-php-daemon:latest --confirm
oc import-image 953 --from unicon/grouper-daemon:latest --confirm
oc import-image 3575 --from yieldr/aws-vpc-hosts-daemon:latest --confirm
oc import-image 7254 --from wpengine/newrelic-php-daemon:latest --confirm
oc import-image 1018 --from pataquets/transmission-daemon:latest --confirm
oc import-image 8880 --from daemoninc/nginxd:latest --confirm
oc import-image 8612 --from sgoings/store-daemon:latest --confirm
oc import-image 1575 --from innovo/ceph-daemon:latest --confirm
oc import-image 7139 --from rucio/rucio-daemons:latest --confirm
oc import-image 1414 --from daemoninc/pypiserverd:latest --confirm
oc import-image 603 --from ojotoxy/densecap-daemon:latest --confirm
oc import-image 5535 --from slpcat/ceph-daemon:latest --confirm
oc import-image 1135 --from dboren/k8-spot-daemon:latest --confirm
oc import-image 2190 --from ojotoxy/neuraltalk-daemon:latest --confirm
oc import-image 2981 --from osism/ceph-daemon:latest --confirm
oc import-image 6112 --from realmicprojects/iridium-daemon:latest --confirm
oc import-image 2216 --from stylight/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 112 --from ajeyvhiremath/infoblox-cni-daemon:latest --confirm
oc import-image 6494 --from crinis/hlxce-daemon:latest --confirm
oc import-image 961 --from mesg/daemon:latest --confirm
oc import-image 1958 --from fabfuel/aws-xray-daemon:latest --confirm
oc import-image 9652 --from corfr/ceph-daemon:latest --confirm
oc import-image 1071 --from dockercloud/network-daemon:latest --confirm
oc import-image 2998 --from danslinky/docker-kubernetes-fluentd-daemonset:latest --confirm
oc import-image 6640 --from ajeyvhiremath/cni-infoblox-daemon:latest --confirm
oc import-image 1352 --from johnsonkoilraj/infoblox-cni-daemon:latest --confirm
oc import-image 1643 --from opennsm/daemonlogger:latest --confirm
oc import-image 9968 --from tbombeg/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 234 --from doofenshmirtz/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 5792 --from rohitshekhar/ceph-daemon:latest --confirm
oc import-image 8186 --from secc/daemon:latest --confirm
oc import-image 7326 --from openmicroscopy/omero-ssh-daemon-c7:latest --confirm
oc import-image 8648 --from flemzord/ceph-daemon:latest --confirm
oc import-image 1713 --from kokhang/loadbalancer-daemon:latest --confirm
oc import-image 6470 --from goodrhys/if-daemon-article-alarm:latest --confirm
oc import-image 3553 --from xeger/aws-xray-daemon:latest --confirm
oc import-image 851 --from lstoll/vpcnet-daemon:latest --confirm
oc import-image 7944 --from pataquets/newrelic-daemon:latest --confirm
oc import-image 6006 --from de13/rpi-ceph-daemon:latest --confirm
oc import-image 1664 --from haor/appsynth-daemon:latest --confirm
oc import-image 5053 --from referup/newrelic-daemon:latest --confirm
oc import-image 7855 --from syncano/fluentd-kubernetes-daemonset:latest --confirm
oc import-image 466 --from daemoninc/oldapd:latest --confirm
oc import-image 7020 --from jiangxj/ceph-daemon:latest --confirm
oc import-image 1816 --from ethereum/client-go:latest --confirm
oc import-image 6128 --from tvelocity/etherpad-lite:latest --confirm
oc import-image 8513 --from ethereum/solc:latest --confirm
oc import-image 5955 --from audreyt/ethercalc:latest --confirm
oc import-image 6592 --from kunstmaan/ethereum-geth:latest --confirm
oc import-image 2773 --from johbo/etherpad-lite:latest --confirm
oc import-image 9462 --from ethereum/client-cpp:latest --confirm
oc import-image 3756 --from ethereum/client-python:latest --confirm
oc import-image 3467 --from sveneh/cpp-ethereum:latest --confirm
oc import-image 9379 --from unihalle/etherpad-lite:latest --confirm
oc import-image 6599 --from centos/etherpad:latest --confirm
oc import-image 9242 --from vertigo/ethereum:latest --confirm
oc import-image 6254 --from fuerst/etherpad-docker:latest --confirm
oc import-image 1525 --from indiehosters/etherpad:latest --confirm
oc import-image 5444 --from kunstmaan/ethereum-geth-devnet:latest --confirm
oc import-image 9561 --from jamesits/etherpad-lite:latest --confirm
oc import-image 9991 --from chevdor/ethereum-testnet-miner:latest --confirm
oc import-image 322 --from fabianwe/etherpad-lite:latest --confirm
oc import-image 2507 --from tendermint/ethermint:latest --confirm
oc import-image 2131 --from kristophjunge/prometheus-etherscan:latest --confirm
oc import-image 9622 --from phocean/etherpad:latest --confirm
oc import-image 9720 --from moss/etherpad:latest --confirm
oc import-image 1885 --from ethercamp/ide:latest --confirm
oc import-image 9317 --from oaeproject/oae-etherpad:latest --confirm
oc import-image 2560 --from ethereumex/eth-netstats:latest --confirm
oc import-image 497 --from dsbaars/go-ethereum-privatechain:latest --confirm
oc import-image 4823 --from anybox/etherdraw:latest --confirm
oc import-image 7659 --from mkodockx/docker-etherpad:latest --confirm
oc import-image 9275 --from kunstmaan/ethereum-geth-testnet:latest --confirm
oc import-image 7414 --from lykkex/lykke-service-ethereumapi:latest --confirm
oc import-image 6484 --from kunstmaan/ethereum-geth-console:latest --confirm
oc import-image 3414 --from willhanau2/cuda-ethereum-mining:latest --confirm
oc import-image 753 --from ethereumclassic/etc-geth:latest --confirm
oc import-image 1785 --from pevtrick/etherpad-lite:latest --confirm
oc import-image 1247 --from ptman/etherpad:latest --confirm
oc import-image 219 --from ansibleapp/etherpad-ansibleapp:latest --confirm
oc import-image 6306 --from 459below/etherdraw:latest --confirm
oc import-image 8928 --from lykkedev/lykke-ethereum-indexer-jobs:latest --confirm
oc import-image 2358 --from rwd1/etherpad:latest --confirm
oc import-image 8312 --from tozd/etherpad:latest --confirm
oc import-image 8141 --from lightcode/etherpad:latest --confirm
oc import-image 1186 --from cbainnovationlab/ethermint:latest --confirm
oc import-image 9610 --from gpul/etherpad:latest --confirm
oc import-image 7624 --from ansibleapp/etherpad-ansibleapp-etherpad:latest --confirm
oc import-image 5776 --from augurproject/go-ethereum:latest --confirm
oc import-image 6577 --from toeirei/etherpad-docker:latest --confirm
oc import-image 9141 --from fusordevel/broken-etherpad:latest --confirm
oc import-image 7187 --from jcrowthe/ethermine_exporter:latest --confirm
oc import-image 3006 --from projectatomic/etherpad-centos7-atomicapp:latest --confirm
oc import-image 7277 --from ethereumex/bootnode-registrar:latest --confirm
oc import-image 399 --from ethereumex/geth-node:latest --confirm
oc import-image 2757 --from lykkedev/lykke-ethereum-indexer-api:latest --confirm
oc import-image 3840 --from lykkex/lykke-service-ethereumjob:latest --confirm
oc import-image 7110 --from xamoc/etherpad:latest --confirm
oc import-image 2402 --from chaingang/ethereal:latest --confirm
oc import-image 6839 --from dymurray/ethereum-console-apb:latest --confirm
oc import-image 8800 --from ethereumex/eth-stats-dashboard:latest --confirm
oc import-image 9731 --from ethereumex/eth-base:latest --confirm
oc import-image 2510 --from maxder/alpine-etherpad:latest --confirm
oc import-image 4487 --from ethereumex/geth-dev:latest --confirm
oc import-image 6105 --from dymurray/ethereum-apb:latest --confirm
oc import-image 1129 --from enettet/ethereum-netstats-api:latest --confirm
oc import-image 1005 --from jpoon/etherchain-light:latest --confirm
oc import-image 4039 --from vkylamba/ethereum:latest --confirm
oc import-image 402 --from kunstmaan/ethereum-eth:latest --confirm
oc import-image 3688 --from rvtraveller/etherdraw:latest --confirm
oc import-image 7553 --from dmonroy/docker-etherpad:latest --confirm
oc import-image 4479 --from wkulhanek/etherpad:latest --confirm
oc import-image 9739 --from ethereumex/azcopy:latest --confirm
oc import-image 6361 --from nasqueron/etherpad:latest --confirm
oc import-image 7090 --from askmike/ethereum-raspbian:latest --confirm
oc import-image 2936 --from chfast/cpp-ethereum-dev:latest --confirm
oc import-image 7988 --from ethereumex/eth-node:latest --confirm
oc import-image 8788 --from itsecur/etherpad-lite:latest --confirm
oc import-image 4644 --from rwd1/ethercalc:latest --confirm
oc import-image 9304 --from oaeproject/oae-etherpad-docker:latest --confirm
oc import-image 1260 --from notaleks/etherpad-lite:latest --confirm
oc import-image 8146 --from enettet/ethereum-node:latest --confirm
oc import-image 1419 --from fusordevel/playbook-etherpad-etherpad:latest --confirm
oc import-image 9052 --from ansibleapp/etherpad-ansibleapp-mariadb:latest --confirm
oc import-image 1487 --from mmitrofan/ethermint:latest --confirm
oc import-image 7847 --from rrana/bits-etherpad:latest --confirm
oc import-image 1596 --from fhardy/etherpad-lite:latest --confirm
oc import-image 6522 --from ethereum/cpp-build-env:latest --confirm
oc import-image 5024 --from satyrius/ethereum-testrpc:latest --confirm
oc import-image 7281 --from webhippie/etherpad:latest --confirm
oc import-image 3546 --from schlomo/etherpad-lite:latest --confirm
oc import-image 8444 --from ansibleapp/etherpad-ansibleapp-nginx:latest --confirm
oc import-image 6391 --from pamplemousse/etherpad:latest --confirm
oc import-image 5578 --from tfiedler/etherpad:latest --confirm
oc import-image 5305 --from oriaks/ethercalc:latest --confirm
oc import-image 1174 --from dymurray/etherpad-cap-atomicapp:latest --confirm
oc import-image 2431 --from fusordevel/etherpad:latest --confirm
oc import-image 3582 --from dimdm/etherpad:latest --confirm
oc import-image 7094 --from etherapis/demos:latest --confirm
oc import-image 9233 --from enettet/ethereum-bootnode:latest --confirm
oc import-image 7526 --from cptobvious/go-ethereum-develop:latest --confirm
oc import-image 2121 --from ansibleplaybookbundle/etherpad-apb:latest --confirm
oc import-image 9537 --from dsbaars/go-ethereum:latest --confirm
oc import-image 3356 --from tendermintdev/ethermint:latest --confirm
oc import-image 3968 --from fingershock/elasticmq:latest --confirm
oc import-image 4677 --from passy/java-repl:latest --confirm
oc import-image 4260 --from fingershock/fakes3:latest --confirm
oc import-image 874 --from fingershock/haproxy-base:latest --confirm
oc import-image 6919 --from mrzahrada/pinger:latest --confirm
oc import-image 2466 --from fingershock/dynamodb-local:latest --confirm
oc import-image 7180 --from andrius/dejavu-docker:latest --confirm
oc import-image 1197 --from wijagels/messenger-home:latest --confirm
oc import-image 1603 --from warenix/web2pdf:latest --confirm
oc import-image 5645 --from stacken/fingerweb:latest --confirm
oc import-image 9420 --from torokati44/worker-fingerprints:latest --confirm
oc import-image 4705 --from fingerpaint/fpm-php7-apache-docker-dev:latest --confirm
oc import-image 7847 --from fingerco/snowplow-enrich:latest --confirm
oc import-image 6640 --from coduno/fingerprint-javaut:latest --confirm
oc import-image 6034 --from fingershock/aws-cli:latest --confirm
oc import-image 7159 --from fingerco/snowplow-collector:latest --confirm
oc import-image 4994 --from fingerco/snowplow-kinesis-s3:latest --confirm
oc import-image 2297 --from fingersoft/fingersoft_hobut:latest --confirm
oc import-image 3742 --from jbrjake/fingerbang:latest --confirm
oc import-image 2853 --from coduno/fingerprint-c:latest --confirm
oc import-image 4072 --from coduno/fingerprint-py:latest --confirm
oc import-image 8531 --from fingerprintsoft/java:latest --confirm
oc import-image 2374 --from fingershock/socat:latest --confirm
oc import-image 5036 --from fingerco/snowplow-es-loader:latest --confirm
oc import-image 7409 --from coduno/fingerprint-java:latest --confirm
oc import-image 2411 --from fingerco/pulsesocial-tracker:latest --confirm
oc import-image 4278 --from fingerland/ts3-server:latest --confirm
oc import-image 4579 --from panyongde/fingertip-qa:latest --confirm
oc import-image 9921 --from fingertoe/c960:latest --confirm
oc import-image 1176 --from coduno/fingerprint-csharp:latest --confirm
oc import-image 5025 --from coduno/fingerprint-cpp:latest --confirm
oc import-image 4696 --from costezki/meteor-fingerprinter:latest --confirm
oc import-image 7310 --from coduno/fingerprint-pascal:latest --confirm
oc import-image 6577 --from coduno/fingerprint-scala:latest --confirm
oc import-image 81 --from coduno/fingerprint-groovy:latest --confirm
oc import-image 7005 --from coduno/fingerprint-js:latest --confirm
oc import-image 725 --from fingerco/snowplow-s3-emr:latest --confirm
oc import-image 1597 --from coduno/fingerprint-go:latest --confirm
oc import-image 3804 --from rahm/location-fingerprint:latest --confirm
oc import-image 8511 --from mrkreig/fingerpint_test:latest --confirm
oc import-image 3715 --from coduno/fingerprint-php:latest --confirm
oc import-image 9313 --from fingerliu/openssh:latest --confirm
oc import-image 7991 --from atentatecnologia/fingerprint:latest --confirm
oc import-image 8366 --from fingerco/analytics-watcher:latest --confirm
oc import-image 9456 --from fingerprintsoft/alpine-glibc:latest --confirm
oc import-image 9236 --from fingersfive/docker-whale:latest --confirm
oc import-image 4515 --from panyongde/fingertip-prod:latest --confirm
oc import-image 2473 --from hofer/logstash-plugins-kafka-mongodb-fingerprint:latest --confirm
oc import-image 5756 --from fingerle/node-sample:latest --confirm
oc import-image 1261 --from illiahapak/fingerprint:latest --confirm
oc import-image 2409 --from dexmediatoll/fingerprint:latest --confirm
oc import-image 7026 --from tuyenuit/finger:latest --confirm
oc import-image 6016 --from ozlevka/build-fingerprint:latest --confirm
oc import-image 1295 --from finger17/personalrepo:latest --confirm
oc import-image 9780 --from pawelgd/fingernet:latest --confirm
oc import-image 8830 --from konstilackner/fingerprinter_api:latest --confirm
oc import-image 8249 --from reddi/finger:latest --confirm
oc import-image 6832 --from fingertip/testexample:latest --confirm
oc import-image 7772 --from dwessling/fatfingerjoe:latest --confirm
oc import-image 3772 --from fingerpaint/fpm-wordpress-dev:latest --confirm
oc import-image 4681 --from fingerpaint/lugpa-server-prod:latest --confirm
oc import-image 4569 --from fingerprintsoft/sahuc-mysql:latest --confirm
oc import-image 7954 --from finger/python:latest --confirm
oc import-image 5167 --from xivoxc/fingerboard:latest --confirm
oc import-image 722 --from 3dechem/kripodb:latest --confirm
oc import-image 6223 --from long25vn/finger:latest --confirm
oc import-image 6297 --from fingerdocker/get-started:latest --confirm
oc import-image 9790 --from anhhuybv/fingerprint:latest --confirm
oc import-image 5099 --from tomaslingotti/fingersnap-0.0.1:latest --confirm
oc import-image 8547 --from gvirtu/fakes3-alpine:latest --confirm
oc import-image 4034 --from vf19cmi/fingertips_dockerfile:latest --confirm
oc import-image 9497 --from fingerbit/get-started:latest --confirm
oc import-image 4942 --from long25vn/fingerprint:latest --confirm
oc import-image 3176 --from rubygem/fingerrails:latest --confirm
oc import-image 4316 --from rubygem/finger:latest --confirm
oc import-image 1372 --from rubygem/fingerpoken:latest --confirm
oc import-image 3751 --from fingermark/test:latest --confirm
oc import-image 4230 --from rubygem/fingerprint:latest --confirm
oc import-image 9929 --from kalyanram262/fingerprint_auth_poc:latest --confirm
oc import-image 5037 --from wodrowcren973t9/fingerbloodpressurec8912:latest --confirm
oc import-image 9086 --from inczocldt1979m4/fingerprintlockscree7905:latest --confirm
oc import-image 3322 --from rubygem/finger-puppet:latest --confirm
oc import-image 4060 --from slifty/audfprint:latest --confirm
oc import-image 2775 --from riccos/docker-ssh:latest --confirm
oc import-image 1616 --from warkommanda/docker-panako:latest --confirm
oc import-image 2140 --from theimpostor/get-jenkins-artifact:latest --confirm
oc import-image 1733 --from tomaslingotti/fingersnap:latest --confirm
oc import-image 5906 --from jinw1990/finger-pop:latest --confirm
oc import-image 5618 --from aesculta/apache2:latest --confirm
oc import-image 5998 --from noodlenut/sqwak:latest --confirm
oc import-image 6170 --from clintmann/network_fingerprint:latest --confirm
oc import-image 3112 --from mfsecurity/aaf-afisd:latest --confirm
oc import-image 5304 --from pfem/metexplore-pathwayenrichment:latest --confirm
oc import-image 2202 --from kharyuk/chemfin-plasp:latest --confirm
oc import-image 8719 --from fingershock/ruby:latest --confirm
oc import-image 7873 --from 5656/test:latest --confirm
oc import-image 6286 --from arielcuomo190k3/morphofingerprintsca1832:latest --confirm
oc import-image 4908 --from gounthar/armv7hf-python-dockerhub:latest --confirm
oc import-image 570 --from bailearle1986h9/thinkpadfingerprintr2654:latest --confirm
oc import-image 8987 --from demccullm1985l9/howdoyougetthemiddle3111:latest --confirm
oc import-image 8375 --from foostan/chef-server-box:latest --confirm
oc import-image 572 --from aretera/foopipes:latest --confirm
oc import-image 6169 --from foobox/memcached:latest --confirm
oc import-image 944 --from foobarto/docker-mumble-server:latest --confirm
oc import-image 8887 --from dorsaydevelopment/foobot-web:latest --confirm
oc import-image 4016 --from x1unix/foodcourt:latest --confirm
oc import-image 8380 --from halkeye/slack-foodee:latest --confirm
oc import-image 6226 --from devux/foodz-dashborad:latest --confirm
oc import-image 1233 --from salaboy/drools-food-services:latest --confirm
oc import-image 8017 --from fooinha/suricata-experimental:latest --confirm
oc import-image 5055 --from dorsaydevelopment/foobot:latest --confirm
oc import-image 7052 --from brianbelljr/fantasy-football:latest --confirm
oc import-image 4057 --from foodcoops/foodsoft:latest --confirm
oc import-image 3268 --from foodsby/node-pip-awscli:latest --confirm
oc import-image 9762 --from jmuraski/foo:latest --confirm
oc import-image 5631 --from hearstat/jenkins-build-foodcritic:latest --confirm
oc import-image 695 --from foolusion/kes:latest --confirm
oc import-image 941 --from sh777/foodsecurityweb:latest --confirm
oc import-image 6961 --from foodpanda/supervisor-healthcheck:latest --confirm
oc import-image 616 --from jonalivi/foodtrucks-web:latest --confirm
oc import-image 4281 --from leastauthority/foolscap-gatherer:latest --confirm
oc import-image 44 --from codeclimate/codeclimate-foodcritic:latest --confirm
oc import-image 2674 --from foobox/php:latest --confirm
oc import-image 8090 --from devuxk/foodz-api:latest --confirm
oc import-image 6429 --from janhalfar/foomo-app-runner:latest --confirm
oc import-image 8400 --from foolusion/elwin-vegeta:latest --confirm
oc import-image 9285 --from nklmish/foodtruck:latest --confirm
oc import-image 6536 --from emccorp/ecs-reduced-footprint:latest --confirm
oc import-image 790 --from foolusion/elwin:latest --confirm
oc import-image 6000 --from endfoos/foosilator:latest --confirm
oc import-image 291 --from foopitech/account:latest --confirm
oc import-image 8633 --from dorsaydevelopment/foobot-telegram:latest --confirm
oc import-image 6974 --from tjshake/foosball-flask:latest --confirm
oc import-image 7110 --from foobert/jwtdummy:latest --confirm
oc import-image 4542 --from signiant/docker-jenkins-centos7-chef-knife-foodcritic:latest --confirm
oc import-image 2233 --from darken/foodcritic:latest --confirm
oc import-image 4570 --from foolusion/hey:latest --confirm
oc import-image 5871 --from foolusion/houston:latest --confirm
oc import-image 2837 --from foobl/php:latest --confirm
oc import-image 1366 --from foobox/mailhog:latest --confirm
oc import-image 8595 --from foodsby/openjdk:latest --confirm
oc import-image 6159 --from sofiyap/tensorflow-stream-food:latest --confirm
oc import-image 3757 --from concourse/deleteme-foo-resource:latest --confirm
oc import-image 544 --from foolusion/easel:latest --confirm
oc import-image 831 --from maniekq/slack-foos-integration:latest --confirm
oc import-image 9447 --from robisenberg/foodtrucks:latest --confirm
oc import-image 7328 --from r2ronoha/foodtrucks-web:latest --confirm
oc import-image 1534 --from foomo/neosproxy:latest --confirm
oc import-image 3743 --from foolusion/elwin-go:latest --confirm
oc import-image 3775 --from foobert/oauth2mock:latest --confirm
oc import-image 1221 --from foolusion/prometheus:latest --confirm
oc import-image 6812 --from rahim888/foodtruckdevenv:latest --confirm
oc import-image 7456 --from foodship/elassandra:latest --confirm
oc import-image 4423 --from mark2222/foodtrucks-web:latest --confirm
oc import-image 6350 --from foobox/mysql-client:latest --confirm
oc import-image 4313 --from foodcoops/haproxy:latest --confirm
oc import-image 8121 --from foospidy/sigsci:latest --confirm
oc import-image 3889 --from foolusion/elwinator:latest --confirm
oc import-image 2223 --from ikuturso/mysql-foo:latest --confirm
oc import-image 7087 --from goodgravy/demo-service-foo:latest --confirm
oc import-image 5639 --from loganbfisher/foodbeacon-api:latest --confirm
oc import-image 4464 --from tnelis/foo:latest --confirm
oc import-image 343 --from foodcoops/certbot:latest --confirm
oc import-image 3610 --from foodtiny/native:latest --confirm
oc import-image 8291 --from foobl/varnish:latest --confirm
oc import-image 8108 --from gratefulclint/food-blogs-migrator:latest --confirm
oc import-image 5250 --from gladcube/gs-front-football:latest --confirm
oc import-image 338 --from bdehamer/foo:latest --confirm
oc import-image 6875 --from foodresearch/bppc:latest --confirm
oc import-image 6979 --from den10/sirisomphone-foods:latest --confirm
oc import-image 4373 --from foodship/ci:latest --confirm
oc import-image 268 --from selfpedia/footballclubservices:latest --confirm
oc import-image 1854 --from ikuturso/foo:latest --confirm
oc import-image 1695 --from jcabillot/foodcritic:latest --confirm
oc import-image 6526 --from football/base:latest --confirm
oc import-image 81 --from foobl/nginx:latest --confirm
oc import-image 7101 --from foodcoopsystem/dev-www:latest --confirm
oc import-image 5393 --from foolusion/bolt-store:latest --confirm
oc import-image 416 --from foolusion/json-gateway:latest --confirm
oc import-image 1905 --from vineeth123/footballclubservices:latest --confirm
oc import-image 4278 --from foolusion/exp-store:latest --confirm
oc import-image 8842 --from foolusion/vegeta:latest --confirm
oc import-image 6547 --from devuxk/foodz-web:latest --confirm
oc import-image 8633 --from 4383/system-service-footprint:latest --confirm
oc import-image 7012 --from foodpedia/foodpedia-ldf:latest --confirm
oc import-image 6527 --from vimagick/foobar:latest --confirm
oc import-image 6353 --from foodityadmin/etcd:latest --confirm
oc import-image 4925 --from prakhar1989/foodtrucks-web:latest --confirm
oc import-image 6953 --from foolusion/gor:latest --confirm
oc import-image 8425 --from foobot/tomcat:latest --confirm
oc import-image 6482 --from foodcoopsat/foodsoft:latest --confirm
oc import-image 7566 --from devcurmudgeon/foo:latest --confirm
oc import-image 1140 --from cyversewarwick/wellington-footprint:latest --confirm
oc import-image 9994 --from foolusion/nqv:latest --confirm
oc import-image 7458 --from pocketplaylab/foo:latest --confirm
oc import-image 7825 --from timmytofu/foo:latest --confirm
oc import-image 6197 --from foobox/wordpress:latest --confirm
oc import-image 4721 --from foodresearch/ngs_intro:latest --confirm
oc import-image 5000 --from foodcoops/sharedlists:latest --confirm
oc import-image 9480 --from dorsaydevelopment/foobot-messenger:latest --confirm
oc import-image 3976 --from mariadb:latest --confirm
oc import-image 9951 --from gcc:latest --confirm
oc import-image 9932 --from bash:latest --confirm
oc import-image 5177 --from marcelmaatkamp/gnuradio:latest --confirm
oc import-image 3754 --from sourcemage:latest --confirm
oc import-image 1462 --from rudism/gnu-social:latest --confirm
oc import-image 4297 --from mbsolutions/tryton-server-gnuhealth:latest --confirm
oc import-image 3196 --from nacyot/prolog-gnu:latest --confirm
oc import-image 4574 --from japaric/x86_64-unknown-linux-gnu:latest --confirm
oc import-image 9297 --from mbessler/gnucash:latest --confirm
oc import-image 3258 --from palshife/gnucash:latest --confirm
oc import-image 8827 --from haggaie/gnuplot:latest --confirm
oc import-image 3908 --from japaric/armv7-unknown-linux-gnueabihf:latest --confirm
oc import-image 7497 --from gnubila/fedehr-anonymizer:latest --confirm
oc import-image 6810 --from marcelmaatkamp/gnuradio-multimode:latest --confirm
oc import-image 6621 --from marcelmaatkamp/gnuradio-gr-gsm-ptrkrys:latest --confirm
oc import-image 518 --from bistromath/gnuradio:latest --confirm
oc import-image 2662 --from billynkid/tryton-server-gnuhealth:latest --confirm
oc import-image 5879 --from morecobol/gnucobol:latest --confirm
oc import-image 983 --from spoonest/gnumeric_docker:latest --confirm
oc import-image 3697 --from mbsolutions/postgres-gnuhealth:latest --confirm
oc import-image 2508 --from japaric/mipsel-unknown-linux-gnu:latest --confirm
oc import-image 8773 --from japaric/aarch64-unknown-linux-gnu:latest --confirm
oc import-image 4924 --from gnubila/mhmd-admin:latest --confirm
oc import-image 5610 --from ngrewe/gnustep-headless-dev:latest --confirm
oc import-image 5575 --from gnumoksha/debian:latest --confirm
oc import-image 1148 --from hengel/docker-latex-gnuplot-inkscape:latest --confirm
oc import-image 3614 --from japaric/powerpc-unknown-linux-gnu:latest --confirm
oc import-image 122 --from noc0lour/gnuradio-buildbot-worker:latest --confirm
oc import-image 4901 --from ngrewe/gnustep-headless-rt:latest --confirm
oc import-image 8729 --from jamesmstone/gnuradio:latest --confirm
oc import-image 2076 --from gnur/ens:latest --confirm
oc import-image 8172 --from japaric/powerpc64-unknown-linux-gnu:latest --confirm
oc import-image 6816 --from japaric/mips-unknown-linux-gnu:latest --confirm
oc import-image 4644 --from japaric/mips64-unknown-linux-gnuabi64:latest --confirm
oc import-image 7494 --from ventosus/universal-linux-gnu:latest --confirm
oc import-image 2691 --from japaric/arm-unknown-linux-gnueabi:latest --confirm
oc import-image 8895 --from japaric/powerpc64le-unknown-linux-gnu:latest --confirm
oc import-image 6708 --from gnur/message-router:latest --confirm
oc import-image 8985 --from japaric/s390x-unknown-linux-gnu:latest --confirm
oc import-image 4871 --from japaric/mips64el-unknown-linux-gnuabi64:latest --confirm
oc import-image 2754 --from purplekarrot/arm-linux-gnueabihf:latest --confirm
oc import-image 5157 --from japaric/i686-unknown-linux-gnu:latest --confirm
oc import-image 7969 --from pgorczak/gnuradio:latest --confirm
oc import-image 4878 --from marcelmaatkamp/pybombs-gnuradio-rtlsdr:latest --confirm
oc import-image 9282 --from gnur/cc2mqtt:latest --confirm
oc import-image 751 --from ventosus/arm-linux-gnueabihf:latest --confirm
oc import-image 3706 --from digitalfreedom/gnukhata:latest --confirm
oc import-image 9115 --from hsaito/gnupg2:latest --confirm
oc import-image 6243 --from smartkit/godpaper-go-score-estimator-gnugo:latest --confirm
oc import-image 7911 --from gnubila/fedehr:latest --confirm
oc import-image 970 --from mrp4p3r/gnu-linux-class:latest --confirm
oc import-image 6054 --from gnumoksha/php-dev:latest --confirm
oc import-image 2964 --from joecox/curl-jq-gnu:latest --confirm
oc import-image 3631 --from ossfuzz/gnutls:latest --confirm
oc import-image 2926 --from arwineap/docker-ubuntu-gnustep:latest --confirm
oc import-image 4439 --from jess/gnuplot:latest --confirm
oc import-image 6819 --from utoft/gnunet:latest --confirm
oc import-image 6392 --from starlabio/arm-linux-gnueabihf:latest --confirm
oc import-image 8624 --from japaric/x86_64-pc-windows-gnu:latest --confirm
oc import-image 1335 --from marcelmaatkamp/pybombs-gnuradio:latest --confirm
oc import-image 5203 --from robotastic/docker-gnuradio:latest --confirm
oc import-image 501 --from nitram509/debian-oraclejdk8-maven-cmake-gcc-gnueabihf:latest --confirm
oc import-image 7398 --from noc0lour/gnuradio-buildbot-master:latest --confirm
oc import-image 9098 --from japaric/sparc64-unknown-linux-gnu:latest --confirm
oc import-image 1585 --from gnur/dowork:latest --confirm
oc import-image 5152 --from hengel/latex-gnuplot-inkscape_debian9:latest --confirm
oc import-image 8377 --from codeclimate/codeclimate-gnu-complexity:latest --confirm
oc import-image 598 --from gnubila/mhmd-documentation:latest --confirm
oc import-image 8597 --from wcurrie/gnuplot:latest --confirm
oc import-image 4298 --from sysrun/gnuradio:latest --confirm
oc import-image 7060 --from marcelmaatkamp/pybombs-gnuradio-gr-gsm:latest --confirm
oc import-image 5082 --from bertlorenz/gnucash-novnc:latest --confirm
oc import-image 8834 --from unlhcc/gnuradio:latest --confirm
oc import-image 5396 --from nicferrier/elnode-gnudoc:latest --confirm
oc import-image 9753 --from ldmbis/gnustep:latest --confirm
oc import-image 2394 --from gnubila/mhmd-upload:latest --confirm
oc import-image 4093 --from gnut3ll4/ttauveron-spark:latest --confirm
oc import-image 2010 --from bradleybossard/docker-gnuspeech:latest --confirm
oc import-image 4450 --from gnupg/amazon-ecs-sample:latest --confirm
oc import-image 4001 --from haggaie/gnuplot-python:latest --confirm
oc import-image 8590 --from gnubila/fedehr-anonymizer-rest:latest --confirm
oc import-image 3628 --from sysrun/gnuradio-sdr:latest --confirm
oc import-image 7775 --from reactorl/gnur-rllvm:latest --confirm
oc import-image 4462 --from bytequest/eclipse-gnuarm-embedded:latest --confirm
oc import-image 9095 --from gnuhub/c-docker:latest --confirm
oc import-image 2382 --from gnur/snost:latest --confirm
oc import-image 4213 --from potz/gnucash:latest --confirm
oc import-image 3399 --from harmish/gnuplot:latest --confirm
oc import-image 1070 --from pachulo/xenial-gnuradio-rtl-toolkit:latest --confirm
oc import-image 3481 --from gnubila/mhmd-central:latest --confirm
oc import-image 9543 --from dbrian/gnupg:latest --confirm
oc import-image 7198 --from rustcross/x86_64-unknown-linux-gnu:latest --confirm
oc import-image 7751 --from gnur/hostsniffer:latest --confirm
oc import-image 561 --from olbat/gnupg:latest --confirm
oc import-image 151 --from japaric/i686-pc-windows-gnu:latest --confirm
oc import-image 3296 --from pavlov99/gnuplot:latest --confirm
oc import-image 8724 --from gnubila/mhmd-driver:latest --confirm
oc import-image 6322 --from exherbo/exherbo-x86_64-pc-linux-gnu-base:latest --confirm
oc import-image 1891 --from jessfraz/gnuplot:latest --confirm
